// Created: 25.03.2021
package io.r2dbc.jdbc;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.springframework.jdbc.core.JdbcOperations;

import io.r2dbc.jdbc.util.DBServerExtension;
import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.test.TestKit;

/**
 * @author Thomas Freese
 */
final class JdbcTestKit implements TestKit<Integer>
{
    /**
     *
     */
    private static ConnectionFactory connectionFactory;

    /**
    *
    */
    @RegisterExtension
    static final DBServerExtension SERVER = new DBServerExtension();

    // /**
    // * @see io.r2dbc.spi.test.TestKit#blobInsert()
    // */
    // @Override
    // @Test
    // public void blobInsert()
    // {
    // // Example.super.blobInsert();
    //
//            // @formatter:off
//            Mono.from(getConnectionFactory().create())
//                .flatMapMany(connection -> Flux.from(connection
//
//                    .createStatement(String.format("INSERT INTO blob_test VALUES (%s)", getPlaceholder(0)))
//                    .bind(getIdentifier(0), Blob.from(Mono.just(StandardCharsets.UTF_8.encode("test-value"))))
//                    .execute())
//
//                    .concatWith(TestKit.close(connection)))
//                .as(StepVerifier::create)
//                .expectNextCount(1).as("rows inserted")
//                .verifyComplete()
//                ;
//            // @formatter:on
    // }

    // /**
    // * @see io.r2dbc.spi.test.TestKit#clobInsert()
    // */
    // @Override
    // @Test
    // public void clobInsert()
    // {
    // // Example.super.clobInsert();
    //
//            // @formatter:off
//            Mono.from(getConnectionFactory().create())
//                .flatMapMany(connection -> Flux.from(connection
//
//                    .createStatement(String.format("INSERT INTO clob_test VALUES (%s)", getPlaceholder(0)))
//                    .bind(getIdentifier(0), Clob.from(Mono.just("test-value")))
//                    .execute())
//
//                    .concatWith(TestKit.close(connection)))
//                .as(StepVerifier::create)
//                .expectNextCount(1).as("rows inserted")
//                .verifyComplete()
//                ;
//         // @formatter:on
    // }

    /**
     * @see io.r2dbc.spi.test.TestKit#bindNull()
     */
    @Override
    @Disabled("Disabled until bindNull is implemented")
    public void bindNull()
    {
        // Empty
    }

    /**
     * @see io.r2dbc.spi.test.TestKit#getConnectionFactory()
     */
    @Override
    public ConnectionFactory getConnectionFactory()
    {
        if (connectionFactory == null)
        {
            connectionFactory = new JdbcConnectionFactory(SERVER.getDataSource());
        }

        return connectionFactory;
    }

    /**
     * @see io.r2dbc.spi.test.TestKit#getCreateTableWithAutogeneratedKey()
     */
    @Override
    public String getCreateTableWithAutogeneratedKey()
    {
        return "CREATE TABLE tbl_auto ( id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1), value INTEGER);";
    }

    /**
     * @see io.r2dbc.spi.test.TestKit#getIdentifier(int)
     */
    @Override
    public Integer getIdentifier(final int index)
    {
        return index;
    }

    /**
     * @see io.r2dbc.spi.test.TestKit#getJdbcOperations()
     */
    @Override
    public JdbcOperations getJdbcOperations()
    {
        return SERVER.getJdbcOperations();
    }

    /**
     * @see io.r2dbc.spi.test.TestKit#getPlaceholder(int)
     */
    @Override
    public String getPlaceholder(final int index)
    {
        return "?";
    }
}